import { NextResponse } from 'next/server'

/**
 * GET /api/agent-report
 *
 * Returns the latest cached agent report produced by run_agent.py.
 * In development, returns a mock report. In production, requires
 * `data/agent_report.json` generated by `python run_agent.py`.
 *
 * Phase 3: Implement real LangGraph agent analysis.
 */

const MOCK_REPORT = {
  status: 'mock',
  generated_at: new Date().toISOString(),
  note: 'Mock report (Phase 3: Replace with real LangGraph agent output)',
  summary: {
    total_articles: 47000,
    analysis_period: '2024-2025',
    key_narratives: [
      {
        narrative: 'Democratic consolidation',
        framing_patterns: ['positive', 'institutional'],
        frequency: 0.32,
      },
      {
        narrative: 'Economic development',
        framing_patterns: ['neutral', 'progress-oriented'],
        frequency: 0.28,
      },
      {
        narrative: 'Regional stability',
        framing_patterns: ['security-focused'],
        frequency: 0.24,
      },
      {
        narrative: 'Social reforms',
        framing_patterns: ['mixed'],
        frequency: 0.16,
      },
    ],
  },
  implementation_note:
    "Run 'python run_agent.py' in Phase 3 to generate real reports from Propaganda.json",
}

const CACHE_HEADERS = {
  'Cache-Control': 'public, s-maxage=3600, stale-while-revalidate=86400',
}

export async function GET() {
  try {
    const report = await import('@/data/agent_report.json')
    if (report.default) {
      return NextResponse.json(report.default, { headers: CACHE_HEADERS })
    }
  } catch {
    // Fall back to mock if file doesn't exist (development)
  }

  return NextResponse.json(MOCK_REPORT, { headers: CACHE_HEADERS })
}
